server:
  port: 8080
fakestore:
  api:
    uri: https://fakestoreapi.com
    paths:
      product: /products
      cart: /carts
      pathVariable:
        id: /{id}
        category: /category/{category}
spring:
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      springframework:
        web: debug